name: LaTeX Build

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Complex LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: assignment.tex
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: assignment.pdf